language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: DNxI3zN0oMOs2erFvPH3BZF8UI5yquQrKePZWAS/EJJU1OLA1zk8cYBvjKqXaEmy3s1j0GNomt9zN8GnzpZz3e4knkh9pMoBqIyu/17kCAcTMS133tdMFRv400SNklqeyeERODhSr3yVxRSIE8HuLs9hLLvzxI3W8syppJ04aSeb1VJhf+b+4IEZqF18Uh1AlaCpTLwll4FHQGyBI9YpLf8wzY4P4+1dci0nKaOf7qulUs+fBbYJiyaopOq818oCZdW9KL/e9LG83Ms5px2Mc+VhgvMvWMHfqF9W8tHWb8dujYezYgQuofrhV72mgvWF10Ah9RTXCcEu6dP/Fv+XAo2jzFcV200K1Iw44BascDUl3aW03bj7ycLPT3D5rHEEPN88b7R5P6dkFrmookoVPjQh6vGeM/N5uEktJMirxnwPm43KJJuCVOOWGGUTZLj0/S+e2UqhAaTmHNb/vPXMsZfmWHYqovl5FcSm/iw3g0Gr8mH6NN7T405EG+mntUkRVP5qz11oGDqiSyH9y+fhFempmfv+YuSaYYVNKRH15YCCKtNO522dI8LNYXt3mHBcx1JZFw59/neHDBcIf0l5jTJKDtEJTazkiTl3qVhepCfiBsJHVYj5xcTO8bXmCeYiuAmYsPxWpUuuPWex5F89ljOK8oY8YLmy11QaeoHMY3Y=
  app: protected-beach-53100
  on:
    repo: katiewest820/hiking-app
